export interface FallbackMenuItem {
  id: string;
  category_id: string;
  name_ka: string;
  name_en: string;
  name_uk: string;
  description_ka?: string;
  description_en?: string;
  description_uk?: string;
  price: string;
  is_available: boolean;
  image_url?: string | null;
  order_index: number;
}

export interface FallbackCategory {
  id: string;
  name_ka: string;
  name_en: string;
  name_uk: string;
  order_index: number;
  items: FallbackMenuItem[];
}

export interface FallbackEvent {
  id: string;
  title_ka: string;
  title_en: string;
  title_uk: string;
  description_ka?: string;
  description_en?: string;
  description_uk?: string;
  event_day_ka: string;
  event_day_en: string;
  event_day_uk: string;
  event_time: string;
  order_index: number;
}

export const FALLBACK_MENU: FallbackCategory[] = [
  {
    id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
    name_ka: 'ხელნაკეთი კოქტეილები — 22₾',
    name_en: 'Hand Crafted Cocktails — 22₾',
    name_uk: 'Авторські коктейлі — 22₾',
    order_index: 0,
    items: [
      {
        id: 'item-4',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'აკადემიკოსი',
        name_en: 'Akademikosi',
        name_uk: 'Академікосі',
        description_ka: 'ბიტერი',
        description_en: 'Bitter',
        description_uk: 'Бітер',
        price: '22',
        is_available: true,
        order_index: 4,
      },
      {
        id: 'item-9',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ამორა',
        name_en: 'Amora',
        name_uk: 'Амора',
        price: '25',
        is_available: true,
        order_index: 9,
      },
      {
        id: 'item-26',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'კენკრის გიმლეტი',
        name_en: 'Berry Gimlet',
        name_uk: 'Ягідний Гімлет',
        description_ka: 'ტროპიკული',
        description_en: 'Tropical',
        description_uk: 'Тропічний',
        price: '22',
        is_available: true,
        order_index: 26,
      },
      {
        id: 'item-29',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ბოტანიკალ დროპი',
        name_en: 'Botanical Drop',
        name_uk: 'Ботанікал Дроп',
        price: '22',
        is_available: true,
        order_index: 29,
      },
      {
        id: 'item-33',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ბაბლ ფრიზი',
        name_en: 'Bubble Freeze',
        name_uk: 'Бабл Фріз',
        description_ka: 'ტროპიკული',
        description_en: 'Tropical',
        description_uk: 'Тропічний',
        price: '22',
        is_available: true,
        order_index: 33,
      },
      {
        id: 'item-41',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'კაიო',
        name_en: 'Cayo',
        name_uk: 'Кайо',
        price: '22',
        is_available: true,
        order_index: 41,
      },
      {
        id: 'item-57',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'დრიმ P',
        name_en: 'Dream P',
        name_uk: 'Дрім P',
        description_ka: 'ტკბილი, კრემოვანი',
        description_en: 'Sweet, Creamy',
        description_uk: 'Солодкий, кремовий',
        price: '22',
        is_available: true,
        order_index: 57,
      },
      {
        id: 'item-69',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ფროზენ სმაილი',
        name_en: 'Frozen Smile',
        name_uk: 'Фрозен Смайл',
        price: '30',
        is_available: true,
        order_index: 69,
      },
      {
        id: 'item-80',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ჰარვესტი',
        name_en: 'Harvest',
        name_uk: 'Харвест',
        description_ka: 'ცხარე, ჩილი',
        description_en: 'Spicy, Chilli',
        description_uk: 'Гострий, чилі',
        price: '22',
        is_available: true,
        order_index: 80,
      },
      {
        id: 'item-107',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'ლუნა',
        name_en: 'Luna',
        name_uk: 'Луна',
        price: '22',
        is_available: true,
        order_index: 107,
      },
      {
        id: 'item-119',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'მოანა',
        name_en: 'Moanaa',
        name_uk: 'Моана',
        price: '25',
        is_available: true,
        order_index: 119,
      },
      {
        id: 'item-144',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'სანსეტი',
        name_en: 'Sunset',
        name_uk: 'Сансет',
        price: '22',
        is_available: true,
        order_index: 144,
      },
      {
        id: 'item-165',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'აკადემიური აპეროლ შპრიცი',
        name_en: 'Academic Spritz',
        name_uk: 'Академічний Апероль Шприц',
        price: '24',
        is_available: true,
        order_index: 165,
      },
      {
        id: 'item-167',
        category_id: '1a8a25c1-6b4d-4952-bbef-8efb0e008441',
        name_ka: 'აურორა',
        name_en: 'Aurora',
        name_uk: 'Аврора',
        price: '22',
        is_available: true,
        order_index: 167,
      },
    ],
  },
  {
    id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
    name_ka: 'კლასიკური კოქტეილები',
    name_en: 'Classic Cocktails',
    name_uk: 'Класичні коктейлі',
    order_index: 1,
    items: [
      {
        id: 'item-14',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'აპეროლ შპრიცი',
        name_en: 'Aperol Spritz',
        name_uk: 'Апероль Шприц',
        price: '25',
        is_available: true,
        order_index: 14,
      },
      {
        id: 'item-18',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ასტი მარტინი ბოთლი',
        name_en: 'Asti Martini Bottle',
        name_uk: 'Асті Мартіні пляшка',
        price: '125',
        is_available: true,
        order_index: 18,
      },
      {
        id: 'item-19',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ბ 52',
        name_en: 'B 52',
        name_uk: 'Б 52',
        price: '19',
        is_available: true,
        order_index: 19,
      },
      {
        id: 'item-21',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ბაზილიკ სმეში',
        name_en: 'Basil Smash',
        name_uk: 'Базилік Смеш',
        price: '20',
        is_available: true,
        order_index: 21,
      },
      {
        id: 'item-22',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მარწყვის ბაზილიკ სმეში',
        name_en: 'Basil smash strawberry',
        name_uk: 'Полуничний Базилік Смеш',
        price: '25',
        is_available: true,
        order_index: 22,
      },
      {
        id: 'item-25',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ბელინი',
        name_en: 'Bellini',
        name_uk: 'Белліні',
        price: '22',
        is_available: true,
        order_index: 25,
      },
      {
        id: 'item-27',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'სისხლიანი მერი',
        name_en: 'Bloody Mary',
        name_uk: 'Кривава Мері',
        price: '22',
        is_available: true,
        order_index: 27,
      },
      {
        id: 'item-30',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ბულვარდიე',
        name_en: 'Boulevardier',
        name_uk: 'Бульвардьє',
        price: '22',
        is_available: true,
        order_index: 30,
      },
      {
        id: 'item-34',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'კაიპირუსკა',
        name_en: 'Caipiruska',
        name_uk: 'Кайпіруска',
        price: '19',
        is_available: true,
        order_index: 34,
      },
      {
        id: 'item-43',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ჭაჭა საუერი',
        name_en: 'Chacha Sour',
        name_uk: 'Чача Сауер',
        price: '19',
        is_available: true,
        order_index: 43,
      },
      {
        id: 'item-50',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'კორპს რევაივერი #2',
        name_en: 'Corpse Reviver #2',
        name_uk: 'Корпс Ревайвер #2',
        price: '20',
        is_available: true,
        order_index: 50,
      },
      {
        id: 'item-52',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'კოსმოპოლიტენი',
        name_en: 'Cosmopolitan',
        name_uk: 'Космополітен',
        price: '20',
        is_available: true,
        order_index: 52,
      },
      {
        id: 'item-53',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'კუბა ლიბრე',
        name_en: 'Cuba Libre',
        name_uk: 'Куба Лібре',
        price: '20',
        is_available: true,
        order_index: 53,
      },
      {
        id: 'item-54',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'დაიკირი',
        name_en: 'Daiquiri',
        name_uk: 'Дайкірі',
        price: '20',
        is_available: true,
        order_index: 54,
      },
      {
        id: 'item-58',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'დრაი მარტინი',
        name_en: 'Dry Martini',
        name_uk: 'Сухий Мартіні',
        price: '20',
        is_available: true,
        order_index: 58,
      },
      {
        id: 'item-62',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ესპრესო მარტინი',
        name_en: 'Espresso Martini',
        name_uk: 'Еспресо Мартіні',
        price: '19',
        is_available: true,
        order_index: 62,
      },
      {
        id: 'item-72',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ჯინ საუერი',
        name_en: 'Gin sour',
        name_uk: 'Джин Сауер',
        price: '20',
        is_available: true,
        order_index: 72,
      },
      {
        id: 'item-73',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ჯინ საუერი მარაკუიათი',
        name_en: 'Gin Sour Maracuya',
        name_uk: 'Джин Сауер Маракуйя',
        price: '22',
        is_available: true,
        order_index: 73,
      },
      {
        id: 'item-77',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ნათლიმამა',
        name_en: 'Godfather',
        name_uk: 'Хрещений батько',
        price: '19',
        is_available: true,
        order_index: 77,
      },
      {
        id: 'item-103',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ლიმონჩელო შპრიცი',
        name_en: 'Limoncello spritz',
        name_uk: 'Лимончело Шприц',
        price: '25',
        is_available: true,
        order_index: 103,
      },
      {
        id: 'item-106',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ლონგ აილენდი',
        name_en: 'Long Island',
        name_uk: 'Лонг Айленд',
        price: '25',
        is_available: true,
        order_index: 106,
      },
      {
        id: 'item-113',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მანჰეტენი',
        name_en: 'Manhattan',
        name_uk: 'Мангеттен',
        price: '20',
        is_available: true,
        order_index: 113,
      },
      {
        id: 'item-114',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მარგარიტა',
        name_en: 'Margarita',
        name_uk: 'Маргарита',
        price: '20',
        is_available: true,
        order_index: 114,
      },
      {
        id: 'item-115',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ვერმუტი მარტინი ბიანკო',
        name_en: 'Martini Bianco',
        name_uk: 'Вермут Мартіні B\'янко',
        price: '10',
        is_available: true,
        order_index: 115,
      },
      {
        id: 'item-116',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ვერმუტი მარტინი როსსო',
        name_en: 'Martini Rosso',
        name_uk: 'Вермут Мартіні Россо',
        price: '10',
        is_available: true,
        order_index: 116,
      },
      {
        id: 'item-118',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მიმოზა',
        name_en: 'Mimosa',
        name_uk: 'Мімоза',
        price: '20',
        is_available: true,
        order_index: 118,
      },
      {
        id: 'item-120',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მოხიტო',
        name_en: 'Mojito',
        name_uk: 'Мохіто',
        price: '20',
        is_available: true,
        order_index: 120,
      },
      {
        id: 'item-124',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ნეგრონი',
        name_en: 'Negroni',
        name_uk: 'Негроні',
        price: '20',
        is_available: true,
        order_index: 124,
      },
      {
        id: 'item-139',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'საიდქარი',
        name_en: 'Sidecar',
        name_uk: 'Сайдкар',
        price: '20',
        is_available: true,
        order_index: 139,
      },
      {
        id: 'item-140',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'საუერი',
        name_en: 'Sour',
        name_uk: 'Сауер',
        price: '6',
        is_available: true,
        order_index: 140,
      },
      {
        id: 'item-142',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'მარწყვის საუერი',
        name_en: 'Strawberry Sour',
        name_uk: 'Полуничний Сауер',
        price: '22',
        is_available: true,
        order_index: 142,
      },
      {
        id: 'item-148',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ტეკილა სანრაიზი',
        name_en: 'Tequila Sunrise',
        name_uk: 'Текіла Санрайз',
        price: '22',
        is_available: true,
        order_index: 148,
      },
      {
        id: 'item-156',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'არაყი მარტინი',
        name_en: 'Vodka Martini',
        name_uk: 'Горілка Мартіні',
        price: '20',
        is_available: true,
        order_index: 156,
      },
      {
        id: 'item-160',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ვისკი საუერი',
        name_en: 'Whiskey Sour',
        name_uk: 'Віскі Сауер',
        price: '20',
        is_available: true,
        order_index: 160,
      },
      {
        id: 'item-176',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'ნივრიანი არაჟანი',
        name_en: 'Garlic sour cream sauce',
        name_uk: 'Часниково-сметанний соус',
        price: '4',
        is_available: true,
        order_index: 176,
      },
      {
        id: 'item-184',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'საუსეპის ჩაი (დიდი ჩაიდანი)',
        name_en: 'Soursop Tea (Large Teapot)',
        name_uk: 'Саусеп чай (великий чайник)',
        price: '14',
        is_available: true,
        order_index: 184,
      },
      {
        id: 'item-185',
        category_id: '2b9b36d2-7c5e-4063-cc0a-9f0c1f119552',
        name_ka: 'საუსეპის ჩაი (პატარა ჩაიდანი)',
        name_en: 'Soursop Tea (Small Teapot)',
        name_uk: 'Саусеп чай (малий чайник)',
        price: '10',
        is_available: true,
        order_index: 185,
      },
    ],
  },
  {
    id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
    name_ka: 'სპირტიანი სასმელები',
    name_en: 'Spirits',
    name_uk: 'Міцні напої',
    order_index: 2,
    items: [
      {
        id: 'item-2',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'არაყი აბსოლუტი ბლუ 50გრ',
        name_en: 'Absolut Blue Vodka 50g',
        name_uk: 'Горілка Абсолют Блу 50г',
        price: '10',
        is_available: true,
        order_index: 2,
      },
      {
        id: 'item-5',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'აკაში იაპონური ვისკი',
        name_en: 'Akashi Japanese Whiskey',
        name_uk: 'Акаші японський віскі',
        price: '30',
        is_available: true,
        order_index: 5,
      },
      {
        id: 'item-7',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ამარეტო დისარონო',
        name_en: 'Amaretto Disaronno',
        name_uk: 'Амаретто Дісаронно',
        price: '14',
        is_available: true,
        order_index: 7,
      },
      {
        id: 'item-10',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ანგოსტურა რომი 7 წლიანი',
        name_en: 'Angostura Rum 7 years',
        name_uk: 'Ром Ангостура 7 років',
        price: '20',
        is_available: true,
        order_index: 10,
      },
      {
        id: 'item-11',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ანგოსტურა რომი რეზერვი',
        name_en: 'Angostura Rum reserved',
        name_uk: 'Ром Ангостура резерв',
        price: '14',
        is_available: true,
        order_index: 11,
      },
      {
        id: 'item-12',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ანგოსტურა რომი სპაისდ',
        name_en: 'Angostura Rum spiced',
        name_uk: 'Ром Ангостура пряний',
        price: '12',
        is_available: true,
        order_index: 12,
      },
      {
        id: 'item-13',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'აპეროლი',
        name_en: 'Aperol',
        name_uk: 'Апероль',
        price: '12',
        is_available: true,
        order_index: 13,
      },
      {
        id: 'item-15',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ასკანელი ბრენდი VS',
        name_en: 'Askaneli Brandy V.S',
        name_uk: 'Бренді Асканелі V.S.',
        price: '12',
        is_available: true,
        order_index: 15,
      },
      {
        id: 'item-16',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ასკანელი ბრენდი VSOP',
        name_en: 'Askaneli Brandy V.S.O.P',
        name_uk: 'Бренді Асканелі V.S.O.P.',
        price: '20',
        is_available: true,
        order_index: 16,
      },
      {
        id: 'item-17',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ასკანელი ბრენდი XO',
        name_en: 'Askaneli Brandy X.O.',
        name_uk: 'Бренді Асканелі X.O.',
        price: '40',
        is_available: true,
        order_index: 17,
      },
      {
        id: 'item-20',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ბეილისი',
        name_en: 'Baileys',
        name_uk: 'Бейліс',
        price: '15',
        is_available: true,
        order_index: 20,
      },
      {
        id: 'item-23',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯინი ბიფიტერი 50გრ',
        name_en: 'Beefeater Gin 50g',
        name_uk: 'Джин Біфітер 50г',
        price: '12',
        is_available: true,
        order_index: 23,
      },
      {
        id: 'item-28',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ბომბეი საფირი',
        name_en: 'Bombay Sapphire',
        name_uk: 'Бомбей Сапфір',
        price: '16',
        is_available: true,
        order_index: 28,
      },
      {
        id: 'item-31',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ბროკერსი',
        name_en: 'Brokers',
        name_uk: 'Брокерс',
        price: '12',
        is_available: true,
        order_index: 31,
      },
      {
        id: 'item-32',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ბროკერს პინკი',
        name_en: 'Brokers Pink',
        name_uk: 'Брокерс Рожевий',
        price: '12',
        is_available: true,
        order_index: 32,
      },
      {
        id: 'item-35',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კალვადოსი VSOP',
        name_en: 'Calvados VSOP',
        name_uk: 'Кальвадос VSOP',
        price: '12',
        is_available: true,
        order_index: 35,
      },
      {
        id: 'item-36',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კამპარი',
        name_en: 'Campari',
        name_uk: 'Кампарі',
        price: '12',
        is_available: true,
        order_index: 36,
      },
      {
        id: 'item-38',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'რომი კაპიტან მორგანი ბლექი 50გრ',
        name_en: 'Captain Morgan Black Rum 50g',
        name_uk: 'Ром Капітан Морган Чорний 50г',
        price: '12',
        is_available: true,
        order_index: 38,
      },
      {
        id: 'item-39',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კაპიტან მორგანი სპაისდ გოლდი',
        name_en: 'Captain Morgan Spiced Gold',
        name_uk: 'Капітан Морган Спайсд Голд',
        price: '12',
        is_available: true,
        order_index: 39,
      },
      {
        id: 'item-40',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კაპიტან მორგანი თეთრი',
        name_en: 'Captain Morgan White',
        name_uk: 'Капітан Морган білий',
        price: '12',
        is_available: true,
        order_index: 40,
      },
      {
        id: 'item-42',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჭაჭა ჯიუაანი',
        name_en: 'Chacha GiuAAni',
        name_uk: 'Чача Джіуаані',
        price: '7',
        is_available: true,
        order_index: 42,
      },
      {
        id: 'item-47',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კუანტრო',
        name_en: 'Cointreau',
        name_uk: 'Куантро',
        price: '16',
        is_available: true,
        order_index: 47,
      },
      {
        id: 'item-48',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ცივი ყავა ბეილისით',
        name_en: 'Cold coffee with Baileys',
        name_uk: 'Холодна кава з Бейліс',
        price: '18',
        is_available: true,
        order_index: 48,
      },
      {
        id: 'item-51',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კორალეხო ტეკილა',
        name_en: 'Corralejo tequila',
        name_uk: 'Текіла Корралехо',
        price: '22',
        is_available: true,
        order_index: 51,
      },
      {
        id: 'item-55',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'დანზკა',
        name_en: 'Danzka',
        name_uk: 'Данзка',
        price: '8',
        is_available: true,
        order_index: 55,
      },
      {
        id: 'item-56',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'დონ ხულიო ბლანკო',
        name_en: 'Don Julio Blanco',
        name_uk: 'Дон Хуліо Бланко',
        price: '40',
        is_available: true,
        order_index: 56,
      },
      {
        id: 'item-65',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ფეიმუს გრაუსი',
        name_en: 'Famous Grouse',
        name_uk: 'Феймос Граус',
        price: '12',
        is_available: true,
        order_index: 65,
      },
      {
        id: 'item-67',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ფრანჯელიკო',
        name_en: 'Frangelico',
        name_uk: 'Франджеліко',
        price: '16',
        is_available: true,
        order_index: 67,
      },
      {
        id: 'item-70',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯინ ბრიზი',
        name_en: 'Gin Breeze',
        name_uk: 'Джин Бриз',
        price: '20',
        is_available: true,
        order_index: 70,
      },
      {
        id: 'item-71',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯინი კანტერა ვერდე',
        name_en: 'Gin Cantera Verde',
        name_uk: 'Джин Кантера Верде',
        price: '17',
        is_available: true,
        order_index: 71,
      },
      {
        id: 'item-74',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯინ ტონიკი',
        name_en: 'Gin Tonic',
        name_uk: 'Джин Тонік',
        price: '19',
        is_available: true,
        order_index: 74,
      },
      {
        id: 'item-75',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯინ ტონიკი მარაკუიათი',
        name_en: 'Gin Tonic Maracuya',
        name_uk: 'Джин Тонік Маракуйя',
        price: '22',
        is_available: true,
        order_index: 75,
      },
      {
        id: 'item-76',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'გლენმორანჯი',
        name_en: 'Glenmorangie',
        name_uk: 'Гленморанджі',
        price: '25',
        is_available: true,
        order_index: 76,
      },
      {
        id: 'item-79',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'გრეი გუსი',
        name_en: 'Grey Goose',
        name_uk: 'Грей Гус',
        price: '22',
        is_available: true,
        order_index: 79,
      },
      {
        id: 'item-81',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჰავანა კლაბი 3 წლის ოქრო',
        name_en: 'Havanna Club 3 Anos Gold',
        name_uk: 'Гавана Клаб 3 роки Голд',
        price: '13',
        is_available: true,
        order_index: 81,
      },
      {
        id: 'item-83',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჰენდრიკსი',
        name_en: 'Hendricks\'s',
        name_uk: 'Хендрікс',
        price: '22',
        is_available: true,
        order_index: 83,
      },
      {
        id: 'item-87',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჰუსონგს ტეკილა',
        name_en: 'Hussong\'s tequila',
        name_uk: 'Текіла Хассонгс',
        price: '35',
        is_available: true,
        order_index: 87,
      },
      {
        id: 'item-88',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯეკ დენიელსი',
        name_en: 'Jack Daniels',
        name_uk: 'Джек Деніелс',
        price: '16',
        is_available: true,
        order_index: 88,
      },
      {
        id: 'item-89',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ლიქიორი იეგერმაისტერი 50გრ',
        name_en: 'Jägermeister 50gr',
        name_uk: 'Лікер Єгермейстер 50г',
        price: '12',
        is_available: true,
        order_index: 89,
      },
      {
        id: 'item-91',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'იეგერმაისტერი წვენით',
        name_en: 'Jagermeister Juice',
        name_uk: 'Єгермейстер з соком',
        price: '19',
        is_available: true,
        order_index: 91,
      },
      {
        id: 'item-92',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჯემესონი',
        name_en: 'Jameson',
        name_uk: 'Джемесон',
        price: '15',
        is_available: true,
        order_index: 92,
      },
      {
        id: 'item-93',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ხოსე კუერვო სილვერი 50გრ',
        name_en: 'Jose Cuervo Silver 50gr',
        name_uk: 'Хосе Куерво Сільвер 50г',
        price: '14',
        is_available: true,
        order_index: 93,
      },
      {
        id: 'item-94',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კალუა',
        name_en: 'Kahlua',
        name_uk: 'Калуа',
        price: '12',
        is_available: true,
        order_index: 94,
      },
      {
        id: 'item-96',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კინაჰანსი',
        name_en: 'Kinahans',
        name_uk: 'Кінахенс',
        price: '12',
        is_available: true,
        order_index: 96,
      },
      {
        id: 'item-97',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კინაჰანს ჰერიტეჯი',
        name_en: 'Kinahans Heritage',
        name_uk: 'Кінахенс Герітейдж',
        price: '25',
        is_available: true,
        order_index: 97,
      },
      {
        id: 'item-104',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ლიმონჩელო',
        name_en: 'Limonchello',
        name_uk: 'Лимончело',
        price: '12',
        is_available: true,
        order_index: 104,
      },
      {
        id: 'item-108',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მაკალანი 12 წლიანი',
        name_en: 'Macallan 12 Y.',
        name_uk: 'Макаллан 12 років',
        price: '65',
        is_available: true,
        order_index: 108,
      },
      {
        id: 'item-109',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მაგდანა ჯინი',
        name_en: 'Magdana Gin',
        name_uk: 'Магдана Джин',
        price: '10',
        is_available: true,
        order_index: 109,
      },
      {
        id: 'item-110',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მაი ტაი',
        name_en: 'Mai Tai',
        name_uk: 'Май Тай',
        price: '22',
        is_available: true,
        order_index: 110,
      },
      {
        id: 'item-112',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მანავი ჯიუაანი',
        name_en: 'Manavi GiuAAni',
        name_uk: 'Манаві Джіуаані',
        price: '14',
        is_available: true,
        order_index: 112,
      },
      {
        id: 'item-117',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მილაგრო სილვერი',
        name_en: 'Milagro Silver',
        name_uk: 'Мілагро Сільвер',
        price: '18',
        is_available: true,
        order_index: 117,
      },
      {
        id: 'item-121',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი მანქი შოულდერი 50გრ',
        name_en: 'Monkey Shoulder Whiskey 50g',
        name_uk: 'Віскі Манкі Шоулдер 50г',
        price: '24',
        is_available: true,
        order_index: 121,
      },
      {
        id: 'item-122',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'მონბლანი',
        name_en: 'Mont Blanc',
        name_uk: 'Монблан',
        price: '26',
        is_available: true,
        order_index: 122,
      },
      {
        id: 'item-125',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ოლდ ფეშენედი',
        name_en: 'Old Fashioned',
        name_uk: 'Олд Фешен',
        price: '20',
        is_available: true,
        order_index: 125,
      },
      {
        id: 'item-129',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'კალვადოსი პაპიდუ VS 50გრ',
        name_en: 'Papidoux VS Calvados 50g',
        name_uk: 'Кальвадос Папіду V.S. 50г',
        price: '11',
        is_available: true,
        order_index: 129,
      },
      {
        id: 'item-130',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'პატრონ ანიეხო',
        name_en: 'Patron Anejo',
        name_uk: 'Патрон Аньєхо',
        price: '40',
        is_available: true,
        order_index: 130,
      },
      {
        id: 'item-131',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'პატრონ რეპოსადო',
        name_en: 'Patron Reposado',
        name_uk: 'Патрон Репосадо',
        price: '45',
        is_available: true,
        order_index: 131,
      },
      {
        id: 'item-132',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'პატრონ სილვერ ტეკილა',
        name_en: 'Patron silver Tequila',
        name_uk: 'Текіла Патрон Сільвер',
        price: '40',
        is_available: true,
        order_index: 132,
      },
      {
        id: 'item-136',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'სან ხოსე',
        name_en: 'San Jose',
        name_uk: 'Сан Хосе',
        price: '12',
        is_available: true,
        order_index: 136,
      },
      {
        id: 'item-137',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'სარაჯიშვილი VS',
        name_en: 'Sarajishvili VS',
        name_uk: 'Сараджішвілі V.S.',
        price: '15',
        is_available: true,
        order_index: 137,
      },
      {
        id: 'item-143',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'შტრო 80',
        name_en: 'Stroh Rum 80',
        name_uk: 'Ром Штро 80',
        price: '18',
        is_available: true,
        order_index: 143,
      },
      {
        id: 'item-146',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ტანკერეი ლონდონ დრაი',
        name_en: 'Tanqueray London dry',
        name_uk: 'Танкерей Лондон Драй',
        price: '15',
        is_available: true,
        order_index: 146,
      },
      {
        id: 'item-147',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ტეკილა დონ ხულიო რეპოსადო',
        name_en: 'Tequila Don Julio Reposado',
        name_uk: 'Текіла Дон Хуліо Репосадо',
        price: '45',
        is_available: true,
        order_index: 147,
      },
      {
        id: 'item-149',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ზე ბოტანისტი',
        name_en: 'The Botanist',
        name_uk: 'Ботаніст',
        price: '22',
        is_available: true,
        order_index: 149,
      },
      {
        id: 'item-153',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი ტულამორ დიუ 50გრ',
        name_en: 'Tullamore Dew Whiskey 50g',
        name_uk: 'Віскі Тулламор Дью 50г',
        price: '15',
        is_available: true,
        order_index: 153,
      },
      {
        id: 'item-154',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'არაყი ენერჯით',
        name_en: 'Vodka Energy',
        name_uk: 'Горілка з енергетиком',
        price: '19',
        is_available: true,
        order_index: 154,
      },
      {
        id: 'item-155',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'არაყი წვენით',
        name_en: 'Vodka Juice',
        name_uk: 'Горілка з соком',
        price: '19',
        is_available: true,
        order_index: 155,
      },
      {
        id: 'item-157',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი ბუნაჰაბენი 12 წლიანი',
        name_en: 'Whiskey Bunnahabhain 12 years',
        name_uk: 'Віскі Буннахабен 12 років',
        price: '45',
        is_available: true,
        order_index: 157,
      },
      {
        id: 'item-158',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი გლენტურეტი 10 წლიანი',
        name_en: 'Whiskey Glenturret 10 years',
        name_uk: 'Віскі Глентуррет 10 років',
        price: '50',
        is_available: true,
        order_index: 158,
      },
      {
        id: 'item-159',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი ლედაიგი სინგლ მოლტი 10 წლიანი',
        name_en: 'Whiskey Ledeig single malt 10 years',
        name_uk: 'Віскі Ледейг сингл молт 10 років',
        price: '40',
        is_available: true,
        order_index: 159,
      },
      {
        id: 'item-161',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'თეთრი ბაკარდი რომი',
        name_en: 'White Bacardi Rum',
        name_uk: 'Білий ром Бакарді',
        price: '12',
        is_available: true,
        order_index: 161,
      },
      {
        id: 'item-162',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ვისკი ვაილდ თარქი 81 პფ 50გრ',
        name_en: 'Wild Turkey 81 PF 50g',
        name_uk: 'Віскі Вайлд Тьоркі 81 PF 50г',
        price: '20',
        is_available: true,
        order_index: 162,
      },
      {
        id: 'item-163',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'აბსენტი ქსენტა აბსენტა 50გრ',
        name_en: 'Xenta Absenta 50g',
        name_uk: 'Абсент Ксента Абсента 50г',
        price: '20',
        is_available: true,
        order_index: 163,
      },
      {
        id: 'item-178',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'რეზონიაკი',
        name_en: 'Rezonyak',
        name_uk: 'Резоньяк',
        price: '9',
        is_available: true,
        order_index: 178,
      },
      {
        id: 'item-201',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჭაჭა ასკანელი ოქრო',
        name_en: 'Chacha Askaneli Gold 50g',
        name_uk: 'Чача Асканелі Голд 50г',
        price: '7',
        is_available: true,
        order_index: 201,
      },
      {
        id: 'item-202',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჭაჭა ვარგა კლასიკი',
        name_en: 'Chacha Varga Classic',
        name_uk: 'Чача Варга Класік',
        price: '12',
        is_available: true,
        order_index: 202,
      },
      {
        id: 'item-203',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჭაჭა ვარგა რეზერვი',
        name_en: 'Chacha Varga Reserve',
        name_uk: 'Чача Варга Резерв',
        price: '14',
        is_available: true,
        order_index: 203,
      },
      {
        id: 'item-206',
        category_id: '3c0c47e3-8d6f-4174-dd1b-af1d2e22a663',
        name_ka: 'ჰენესი VS 50 გრ',
        name_en: 'Hennessy VS 50g',
        name_uk: 'Коньяк Хеннессі V.S. 50г',
        price: '30',
        is_available: true,
        order_index: 206,
      },
    ],
  },
  {
    id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
    name_ka: 'ლუდი',
    name_en: 'Beer',
    name_uk: 'Пиво',
    order_index: 3,
    items: [
      {
        id: 'item-24',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ლუდის შემწვარი დაფა',
        name_en: 'Beer fried board',
        name_uk: 'Пивна тарілка фрі',
        price: '60',
        is_available: true,
        order_index: 24,
      },
      {
        id: 'item-49',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ლუდი კორონა',
        name_en: 'Corona beer',
        name_uk: 'Пиво Корона',
        price: '15',
        is_available: true,
        order_index: 49,
      },
      {
        id: 'item-59',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ერდინგერ ბლექი',
        name_en: 'Erdinger black',
        name_uk: 'Ердінгер темне',
        price: '14',
        is_available: true,
        order_index: 59,
      },
      {
        id: 'item-60',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ერდინგერ ბრაუჰაუსი',
        name_en: 'Erdinger Brauhaus',
        name_uk: 'Ердінгер Браухаус',
        price: '18',
        is_available: true,
        order_index: 60,
      },
      {
        id: 'item-64',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ესტრეია',
        name_en: 'Estrella',
        name_uk: 'Естрелла',
        price: '13',
        is_available: true,
        order_index: 64,
      },
      {
        id: 'item-82',
        category_id: '4d1d58f4-9e7a-4285-ee2c-bf2e3f33b774',
        name_ka: 'ჰაინეკენი',
        name_en: 'Heineken',
        name_uk: 'Хайнекен',
        price: '12',
        is_available: true,
        order_index: 82,
      },
    ],
  },
  {
    id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
    name_ka: 'უალკოჰოლო სასმელები',
    name_en: 'Soft Drinks',
    name_uk: 'Безалкогольні напої',
    order_index: 4,
    items: [
      {
        id: 'item-0',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'ტონიკი',
        name_en: 'Tonic water',
        name_uk: 'Тонік',
        price: '6',
        is_available: true,
        order_index: 0,
      },
      {
        id: 'item-84',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'სახლის ლიმონათი კენკრით',
        name_en: 'Homemade berry lemonade',
        name_uk: 'Домашній ягідний лимонад',
        price: '15',
        is_available: true,
        order_index: 84,
      },
      {
        id: 'item-85',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'სახლის ლიმონათი ლიმონით და პიტნით',
        name_en: 'Homemade lemon & mint lemonade',
        name_uk: 'Домашній лимонад лимон-м\'ята',
        price: '12',
        is_available: true,
        order_index: 85,
      },
      {
        id: 'item-86',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'სახლის ლიმონათი მარაკუიათი',
        name_en: 'Homemade passion fruit lemonade',
        name_uk: 'Домашній лимонад маракуйя',
        price: '15',
        is_available: true,
        order_index: 86,
      },
      {
        id: 'item-90',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'იეგერმაისტერი ენერჯი',
        name_en: 'Jagermeister Energy',
        name_uk: 'Єгермейстер Енерджі',
        price: '20',
        is_available: true,
        order_index: 90,
      },
      {
        id: 'item-105',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'ლონგ ენერჯი',
        name_en: 'Long Energy',
        name_uk: 'Лонг Енерджі',
        price: '30',
        is_available: true,
        order_index: 105,
      },
      {
        id: 'item-134',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'რედ ბული ყვითელი',
        name_en: 'Red bull yellow',
        name_uk: 'Ред Булл жовтий',
        price: '12',
        is_available: true,
        order_index: 134,
      },
      {
        id: 'item-164',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'XL',
        name_en: 'XL',
        name_uk: 'XL',
        price: '8',
        is_available: true,
        order_index: 164,
      },
      {
        id: 'item-171',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'კოკა კოლა',
        name_en: 'Coca-Cola',
        name_uk: 'Кока-Кола',
        price: '5',
        is_available: true,
        order_index: 171,
      },
      {
        id: 'item-199',
        category_id: '5e2e6905-0f8b-4396-ff3d-cf3f4f44c885',
        name_ka: 'წვენი',
        name_en: 'Juice',
        name_uk: 'Сік',
        price: '5',
        is_available: true,
        order_index: 199,
      },
    ],
  },
  {
    id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
    name_ka: 'ყავა და ჩაი',
    name_en: 'Coffee & Tea',
    name_uk: 'Кава та чай',
    order_index: 5,
    items: [
      {
        id: 'item-8',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'ამერიკანო',
        name_en: 'Americano',
        name_uk: 'Американо',
        price: '8',
        is_available: true,
        order_index: 8,
      },
      {
        id: 'item-37',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'კაპუჩინო',
        name_en: 'Cappuccino',
        name_uk: 'Капучино',
        price: '10',
        is_available: true,
        order_index: 37,
      },
      {
        id: 'item-61',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'ესპრესო',
        name_en: 'Espresso',
        name_uk: 'Еспресо',
        price: '6',
        is_available: true,
        order_index: 61,
      },
      {
        id: 'item-63',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'ესპრესო მარაკუია ტონიკი',
        name_en: 'Espresso tonic Maracuja',
        name_uk: 'Еспресо тонік Маракуйя',
        price: '16',
        is_available: true,
        order_index: 63,
      },
      {
        id: 'item-102',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'ლატე',
        name_en: 'Latte',
        name_uk: 'Лате',
        price: '14',
        is_available: true,
        order_index: 102,
      },
      {
        id: 'item-173',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'მთის შავი ცეილონი (დიდი ჩაიდანი)',
        name_en: 'Mountain Black Ceylon (Large Teapot)',
        name_uk: 'Гірський чорний цейлон (великий чайник)',
        price: '14',
        is_available: true,
        order_index: 173,
      },
      {
        id: 'item-174',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'მთის შავი ცეილონი (პატარა ჩაიდანი)',
        name_en: 'Mountain Black Ceylon (Small Teapot)',
        name_uk: 'Гірський чорний цейлон (малий чайник)',
        price: '10',
        is_available: true,
        order_index: 174,
      },
      {
        id: 'item-182',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'სამეფო დესერტი (დიდი ჩაიდანი)',
        name_en: 'Royal Dessert (Large Teapot)',
        name_uk: 'Королівський десерт (великий чайник)',
        price: '14',
        is_available: true,
        order_index: 182,
      },
      {
        id: 'item-183',
        category_id: '6f3f7a16-1a9c-44a7-8a4e-df4f5c55d996',
        name_ka: 'სამეფო დესერტი (პატარა ჩაიდანი)',
        name_en: 'Royal Dessert (Small Teapot)',
        name_uk: 'Королівський десерт (малий чайник)',
        price: '10',
        is_available: true,
        order_index: 183,
      },
    ],
  },
  {
    id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
    name_ka: 'ღვინო',
    name_en: 'Wine',
    name_uk: 'Вино',
    order_index: 6,
    items: [
      {
        id: 'item-1',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'წინანდალი ფესვები',
        name_en: 'Tsinandali Pesvebi',
        name_uk: 'Цинандалі Песвебі',
        price: '12',
        is_available: true,
        order_index: 1,
      },
      {
        id: 'item-6',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ალკანაიძე',
        name_en: 'Alkanaidze',
        name_uk: 'Алканаїдзе',
        price: '13',
        is_available: true,
        order_index: 6,
      },
      {
        id: 'item-78',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'გორული მწვანე კავთის ღვინო',
        name_en: 'Goruli Mtsvane Kavta Wine',
        name_uk: 'Горулі Мцване Кавта Вайн',
        price: '16',
        is_available: true,
        order_index: 78,
      },
      {
        id: 'item-98',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ქინძმარაული ბოთლი ბეროზა',
        name_en: 'Kindzmarauli bottle Beroza',
        name_uk: 'Кіндзмараулі пляшка Бероза',
        price: '60',
        is_available: true,
        order_index: 98,
      },
      {
        id: 'item-99',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ქისი ჯიუაანი',
        name_en: 'Kisi GiuAAni',
        name_uk: 'Кісі Джіуаані',
        price: '14',
        is_available: true,
        order_index: 99,
      },
      {
        id: 'item-100',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'კრახუნა',
        name_en: 'Krakhuna',
        name_uk: 'Крахуна',
        price: '16',
        is_available: true,
        order_index: 100,
      },
      {
        id: 'item-101',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ლაფით დე ფით',
        name_en: 'Lafitte de fit',
        name_uk: 'Лафіт де фіт',
        price: '20',
        is_available: true,
        order_index: 101,
      },
      {
        id: 'item-123',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'მწვანე ქვევრი ჩური ჩინებული',
        name_en: 'Mtsvane Qvevri Churi Chinebuli',
        name_uk: 'Мцване Квеврі Чурі Чинебулі',
        price: '15',
        is_available: true,
        order_index: 123,
      },
      {
        id: 'item-138',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'შავკაპიტო აგიდელა',
        name_en: 'Shavkapito Agidela',
        name_uk: 'Шавкапіто Агідела',
        price: '17',
        is_available: true,
        order_index: 138,
      },
      {
        id: 'item-152',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ცოლიკაური ჩური ჩინებული',
        name_en: 'Tsolikauri Churi Chinebuli',
        name_uk: 'Цолікаурі Чурі Чинебулі',
        price: '17',
        is_available: true,
        order_index: 152,
      },
      {
        id: 'item-166',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ალექსანდროული ფესვები',
        name_en: 'Aleksandrouli Pesvebi',
        name_uk: 'Александроулі Песвебі',
        price: '16',
        is_available: true,
        order_index: 166,
      },
      {
        id: 'item-168',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ახმეტელი ჭაჭა',
        name_en: 'Akhmeteli Chacha',
        name_uk: 'Ахметелі Чача',
        price: '8',
        is_available: true,
        order_index: 168,
      },
      {
        id: 'item-170',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'კახური მწვანე ახმეტელი',
        name_en: 'Kakhuri Mtsvane Akhmeteli',
        name_uk: 'Кахурі Мцване Ахметелі',
        price: '14',
        is_available: true,
        order_index: 170,
      },
      {
        id: 'item-172',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'კრახუნა ფესვები',
        name_en: 'Krakhuna Pesvebi',
        name_uk: 'Крахуна Песвебі',
        price: '15',
        is_available: true,
        order_index: 172,
      },
      {
        id: 'item-175',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'მუკუზანი წითელი მშრალი (ჭიქა) ახმეტელი',
        name_en: 'Mukuzani Red Dry Akhmeteli (Glass)',
        name_uk: 'Мукузані червоне сухе Ахметелі (бокал)',
        price: '14',
        is_available: true,
        order_index: 175,
      },
      {
        id: 'item-177',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ოჯალეში (წითელი ნახევრად ტკბილი) - BEROZA MARANI (ჭიქა)',
        name_en: 'Ojaleshi Semi-Sweet Red - BEROZA MARANI (Glass)',
        name_uk: 'Оджалеші напівсолодке червоне - BEROZA MARANI (бокал)',
        price: '15',
        is_available: true,
        order_index: 177,
      },
      {
        id: 'item-179',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'როზე (ნახევრად ტკბილი) - OneLove (ჭიქა)',
        name_en: 'Rose Semi-Sweet - OneLove (Glass)',
        name_uk: 'Рожеве напівсолодке - OneLove (бокал)',
        price: '13',
        is_available: true,
        order_index: 179,
      },
      {
        id: 'item-180',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'როზე (ნახევრად ტკბილი) - OneLove (ბოთლი)',
        name_en: 'Rose Semi-Sweet - OneLove (Bottle)',
        name_uk: 'Рожеве напівсолодке - OneLove (пляшка)',
        price: '65',
        is_available: true,
        order_index: 180,
      },
      {
        id: 'item-181',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'რქაწითელი ახმეტელი',
        name_en: 'Rkatsiteli Akhmeteli',
        name_uk: 'Ркацителі Ахметелі',
        price: '14',
        is_available: true,
        order_index: 181,
      },
      {
        id: 'item-186',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'საფერავი პეტრა',
        name_en: 'Saperavi Petra',
        name_uk: 'Сапераві Петра',
        price: '15',
        is_available: true,
        order_index: 186,
      },
      {
        id: 'item-187',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'საფერავი პრემიუმი ფესვები',
        name_en: 'Saperavi Premium Pesvebi',
        name_uk: 'Сапераві Преміум Песвебі',
        price: '15',
        is_available: true,
        order_index: 187,
      },
      {
        id: 'item-188',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'საფერავი წითელი მშრალი ახმეტელი',
        name_en: 'Saperavi Red Dry Akhmeteli',
        name_uk: 'Сапераві червоне сухе Ахметелі',
        price: '13',
        is_available: true,
        order_index: 188,
      },
      {
        id: 'item-189',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ტვიში გიუანი',
        name_en: 'Tvishi Giuaani',
        name_uk: 'Твіші Джіуаані',
        price: '15',
        is_available: true,
        order_index: 189,
      },
      {
        id: 'item-190',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ტვიში ფესვები',
        name_en: 'Tvishi Pesvebi',
        name_uk: 'Твіші Песвебі',
        price: '16',
        is_available: true,
        order_index: 190,
      },
      {
        id: 'item-195',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ქინძმარაული ფესვები',
        name_en: 'Kindzmarauli Pesvebi',
        name_uk: 'Кіндзмараулі Песвебі',
        price: '14',
        is_available: true,
        order_index: 195,
      },
      {
        id: 'item-196',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ქინძმარაული (წითელი ნახევრად ტკბილი) - BEROZA MARANI (ჭიქა)',
        name_en: 'Kindzmarauli Semi-Sweet Red - BEROZA MARANI (Glass)',
        name_uk: 'Кіндзмараулі напівсолодке червоне - BEROZA MARANI (бокал)',
        price: '12',
        is_available: true,
        order_index: 196,
      },
      {
        id: 'item-197',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ქისი თეთრი მშრალი ახმეტელი',
        name_en: 'Kisi White Dry Akhmeteli',
        name_uk: 'Кісі біле сухе Ахметелі',
        price: '14',
        is_available: true,
        order_index: 197,
      },
      {
        id: 'item-198',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ცოლიკაური (თეთრი მშრალი) - BEROZA MARANI (ჭიქა)',
        name_en: 'Tsolikauri Dry White - BEROZA MARANI (Glass)',
        name_uk: 'Цолікаурі сухе біле - BEROZA MARANI (бокал)',
        price: '12',
        is_available: true,
        order_index: 198,
      },
      {
        id: 'item-200',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'წინანდალი თეთრი მშრალი (ჭიქა) ახმეტელი',
        name_en: 'Tsinandali White Dry Akhmeteli (Glass)',
        name_uk: 'Цинандалі біле сухе Ахметелі (бокал)',
        price: '12',
        is_available: true,
        order_index: 200,
      },
      {
        id: 'item-204',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ხვანჭკარა ფესვები',
        name_en: 'Khvanchkara Pesvebi',
        name_uk: 'Хванчкара Песвебі',
        price: '16',
        is_available: true,
        order_index: 204,
      },
      {
        id: 'item-205',
        category_id: '7a4a8b27-2b0d-45b8-bb5f-ef5f6f66e007',
        name_ka: 'ხვანჭკარა (წითელი ნახევრად ტკბილი) - BEROZA MARANI (ბოთლი)',
        name_en: 'Khvanchkara Semi-Sweet Red - BEROZA MARANI (Bottle)',
        name_uk: 'Хванчкара напівсолодке червоне - BEROZA MARANI (пляшка)',
        price: '16',
        is_available: true,
        order_index: 205,
      },
    ],
  },
  {
    id: '8b5b9c38-3c1e-46c9-cc6f-ff6f7e77f118',
    name_ka: 'ცქრიალა ღვინო',
    name_en: 'Sparkling Wine',
    name_uk: 'Ігристе вино',
    order_index: 7,
    items: [
      {
        id: 'item-111',
        category_id: '8b5b9c38-3c1e-46c9-cc6f-ff6f7e77f118',
        name_ka: 'მაჯესტა ბრუტი ცქრიალა ღვინო',
        name_en: 'Majesta Brut sparkling wine',
        name_uk: 'Маджеста Брют ігристе вино',
        price: '60',
        is_available: true,
        order_index: 111,
      },
      {
        id: 'item-133',
        category_id: '8b5b9c38-3c1e-46c9-cc6f-ff6f7e77f118',
        name_ka: 'პროსეკო მილესიმუტო',
        name_en: 'Prosecco Millesimato',
        name_uk: 'Просекко Міллезімато',
        price: '75',
        is_available: true,
        order_index: 133,
      },
      {
        id: 'item-150',
        category_id: '8b5b9c38-3c1e-46c9-cc6f-ff6f7e77f118',
        name_ka: 'ტოსტი ბატერფლაი ცქრიალა ღვინო ბოთლი',
        name_en: 'Tosti Butterfly Sparkling Wine bottle',
        name_uk: 'Тості Батерфляй ігристе вино пляшка',
        price: '85',
        is_available: true,
        order_index: 150,
      },
      {
        id: 'item-151',
        category_id: '8b5b9c38-3c1e-46c9-cc6f-ff6f7e77f118',
        name_ka: 'ტოსტი პროსეკო ექსტრა დრაი ბოთლი',
        name_en: 'Tosti Prosecco Extra Dry Bottle',
        name_uk: 'Тості Просекко екстра драй пляшка',
        price: '85',
        is_available: true,
        order_index: 151,
      },
    ],
  },
  {
    id: '9c6c0d49-4d2f-47da-ad7a-0a7a8d88e229',
    name_ka: 'სალათები',
    name_en: 'Salads',
    name_uk: 'Салати',
    order_index: 8,
    items: [
    ],
  },
  {
    id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
    name_ka: 'სნექები',
    name_en: 'Snacks',
    name_uk: 'Закуски',
    order_index: 9,
    items: [
      {
        id: 'item-44',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ყველის ბურთები',
        name_en: 'Cheese balls',
        name_uk: 'Сирні кульки',
        price: '16',
        is_available: true,
        order_index: 44,
      },
      {
        id: 'item-45',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ყველის ჩხირები',
        name_en: 'Cheese Sticks',
        name_uk: 'Сирні палички',
        price: '14',
        is_available: true,
        order_index: 45,
      },
      {
        id: 'item-46',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ქათმის ბაიტსები',
        name_en: 'Chicken bites',
        name_uk: 'Курячі байтси',
        price: '15',
        is_available: true,
        order_index: 46,
      },
      {
        id: 'item-66',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ფიშ ენდ ჩიფსი',
        name_en: 'Fish and chips',
        name_uk: 'Фіш енд чіпс',
        price: '25',
        is_available: true,
        order_index: 66,
      },
      {
        id: 'item-68',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'კარტოფილი ფრი ყველის სოსუით',
        name_en: 'French fries with cheese sauce',
        name_uk: 'Картопля фрі з сирним соусом',
        price: '12',
        is_available: true,
        order_index: 68,
      },
      {
        id: 'item-95',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'კეტჩუპი',
        name_en: 'Ketchup',
        name_uk: 'Кетчуп',
        price: '3',
        is_available: true,
        order_index: 95,
      },
      {
        id: 'item-126',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ხახვის რგოლები',
        name_en: 'Onion rings',
        name_uk: 'Цибулеві кільця',
        price: '12',
        is_available: true,
        order_index: 126,
      },
      {
        id: 'item-141',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'შესუნელებული ფრი',
        name_en: 'Spiced French fries',
        name_uk: 'Картопля фрі зі спеціями',
        price: '10',
        is_available: true,
        order_index: 141,
      },
      {
        id: 'item-145',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ტკბილცხარე სოუსი',
        name_en: 'Sweet chili',
        name_uk: 'Солодкий чилі',
        price: '4',
        is_available: true,
        order_index: 145,
      },
      {
        id: 'item-169',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'კარტოფილი ფრი',
        name_en: 'French fries',
        name_uk: 'Картопля фрі',
        price: '8',
        is_available: true,
        order_index: 169,
      },
      {
        id: 'item-191',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ქათმის ფრთები ყველის სოუსით',
        name_en: 'Chicken Wings with Cheese Sauce',
        name_uk: 'Курячі крильця з сирним соусом',
        price: '18',
        is_available: true,
        order_index: 191,
      },
      {
        id: 'item-192',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ქათმის ფრთები',
        name_en: 'Chicken Wings',
        name_uk: 'Курячі крильця',
        price: '14',
        is_available: true,
        order_index: 192,
      },
      {
        id: 'item-193',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ქათმის ფრთები აზიურად',
        name_en: 'Asian-style Chicken Wings',
        name_uk: 'Курячі крильця по-азійськи',
        price: '16',
        is_available: true,
        order_index: 193,
      },
      {
        id: 'item-194',
        category_id: '0d7d1e50-5e3a-48eb-ad8b-1b8b9f99a330',
        name_ka: 'ქათმის ფრთები აჯიკით',
        name_en: 'Chicken Wings with Adjika',
        name_uk: 'Курячі крильця з аджикою',
        price: '16',
        is_available: true,
        order_index: 194,
      },
    ],
  },
  {
    id: '1e8e2f61-6f4b-49fc-be9c-2c9c0d00f441',
    name_ka: 'პიცა და ცომეული',
    name_en: 'Pizza & Dough',
    name_uk: 'Піца та випічка',
    order_index: 10,
    items: [
      {
        id: 'item-127',
        category_id: '1e8e2f61-6f4b-49fc-be9c-2c9c0d00f441',
        name_ka: 'ტაფის ხაჭაპური',
        name_en: 'Pan Khachapuri',
        name_uk: 'Пательня Хачапурі',
        price: '18',
        is_available: true,
        order_index: 127,
      },
      {
        id: 'item-128',
        category_id: '1e8e2f61-6f4b-49fc-be9c-2c9c0d00f441',
        name_ka: 'ტაფის ხაჭაპური შებოლილი სულგუნით',
        name_en: 'Pan Khachapuri with smoked Sulguni',
        name_uk: 'Пательня Хачапурі з копченим сулугуні',
        price: '20',
        is_available: true,
        order_index: 128,
      },
    ],
  },
  {
    id: '2f9f3a72-7a5c-40fd-afad-3dad1c11a552',
    name_ka: 'ბურგერები და სენდვიჩები',
    name_en: 'Burgers & Sandwiches',
    name_uk: 'Бургери та сендвічі',
    order_index: 11,
    items: [
    ],
  },
  {
    id: '3a0a4b83-8b6d-41fe-afbe-4ebe2b22e663',
    name_ka: 'დესერტები',
    name_en: 'Desserts',
    name_uk: 'Десерти',
    order_index: 12,
    items: [
    ],
  },
];

export const FALLBACK_EVENTS: FallbackEvent[] = [
  {
    id: 'ev-1',
    title_ka: 'Underground Jam',
    title_en: 'Underground Jam',
    title_uk: 'Underground Jam',
    description_ka: 'ღია მიკროფონი',
    description_en: 'Open Mic Night',
    description_uk: 'Відкритий мікрофон',
    event_day_ka: 'ოთხშაბათი',
    event_day_en: 'Wednesday',
    event_day_uk: 'Середа',
    event_time: '21:00',
    order_index: 0,
  },
  {
    id: 'ev-2',
    title_ka: 'Jupiter Nights',
    title_en: 'Jupiter Nights',
    title_uk: 'Jupiter Nights',
    description_ka: 'DJ სეტი',
    description_en: 'DJ Set',
    description_uk: 'DJ сет',
    event_day_ka: 'პარასკევი',
    event_day_en: 'Friday',
    event_day_uk: "П'ятниця",
    event_time: '23:00',
    order_index: 1,
  },
  {
    id: 'ev-3',
    title_ka: 'ცოცხალი მუსიკა',
    title_en: 'Live Bands',
    title_uk: 'Живі гурти',
    description_ka: 'მოწვეული არტისტები',
    description_en: 'Featured Artists',
    description_uk: 'Запрошені არтисти',
    event_day_ka: 'შაბათი',
    event_day_en: 'Saturday',
    event_day_uk: 'Субота',
    event_time: '22:00',
    order_index: 2,
  },
];